### ISSUE TITLE
Nextera XT DNA Library Prep Kit Protocol: Part 4/4 - Pool Libraries

### ISSUE THREAD

**Issue by kristinellis** [Opentrons/Protocols#1251]
- Convert from APIv1-->APIv2
- Update from labware V1 to labware V2
- Review content for necessary updates (ie, Materials section: consistent format + links)

**Protocol:** https://protocols.opentrons.com/protocol/illumina-nextera-XT-library-prep-part4

**Comment by chazmanc** [comment]
closed in #1338
