### ISSUE TITLE
otcustomizers not recognized by OT2 running opentrons api version 3.2.0

### ISSUE THREAD

**Issue by glebkuznetsov** [Opentrons/Protocols#290]
Many of the example protocols import from otcustomizers, but this package is not installed by default on the OT2

**Comment by IanLondon** [comment]
Hello Gleb, thanks for submitting this issue.

Right now, `otcustomizers` is only used in protocols that feed our [Protocol Library website](http://protocols.opentrons.com), specifically for protocols with customizable fields. The `otcustomizers` are used to create type annotations, which in turn are used to convert the `run_custom_protocol` function to form fields on that website. The robot shouldn't ever use `otcustomizers`, it's only intended for use by the Protocol Library web app's backend to handle form creation. When a user downloads a protocol from the Protocol Library, the `otcustomizers` is stripped out and the values from the form are passed as arguments into the protocol's `run_custom_protocol` function.

If you'd like to download protocols from the library on this repo and run them directly, if they use customizable fields, you'd need to delete `otcustomizers` and also add a line like `run_custom_protocol(something=10, another_thing=15)` (or just `run_custom_protocol()` to use its default arguments).  Or you could download the protocol off the website, where `otcustomizers` is already stripped out.

If the protocol doesn't use customizable fields, then no modifications are needed and these can be downloaded directly from this repo and run as-is.

In the future we are thinking of different ways to support customizations in the Run App for both Python and JSON protocol formats.

Please let me know if this doesn't solve your problem or if I misunderstood what you are looking for.

**Comment by glebkuznetsov** [comment]
Thanks for clarifying Ian.

Is there a way for me to leverage the web app backend code myself to generate these forms?

Related question, can I leverage the backend to add a csv upload form? I found this post that instructs to go through you guys to have a protocol made for us. But is this something we can do ourselves?
https://support.opentrons.com/ot-2/protocol-development-for-ot2/custom-protocol-guidelines-csv-input-files

Thanks!

**Comment by glebkuznetsov** [comment]
Ah, I see: the csv upload form gets added to <protocols.opentrons.com> (e.g. <https://protocols.opentrons.com/protocol/dna_normalization_csv>) and then your server generates a single .py file for download by the user with csv entries hard-coded.

I was expecting a csv upload form to appear in the Opentrons driver app. And likewise for other otcustomizers. Is there support for something like that?

Thank you.

**Comment by Laura-Danielle** [comment]
Hi!

That is not currently a feature supported in our Run App, but if you would like you can open an issue [here ](https://github.com/OpenTrons/opentrons)or try to contribute your own feature. You would just need to build out an http endpoint which can add files onto the robot at a minimum.
