### ISSUE TITLE
Replace containers.create with labware.create in all OT2 protocols

### ISSUE THREAD

**Issue by IanLondon** [Opentrons/Protocols#346]
Older OT2 protocols like http://protocols.opentrons.com/protocol/dinosaur were written using `containers.create` won't be parsed properly by protolib2. They need to be changed to use `labware.create`

OT1 protocols should not be changed

**Comment by Laura-Danielle** [comment]
Oops didn't realize this was a ticket. Closed in PR 348 and 378
