### ISSUE TITLE
[M] Tam Tran at Griffith University

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/Protocols#408]
https://trello.com/c/Zyf8IiT9/1291-s-tam-tran-at-griffith-university2018-10-15T16:00:00.000ZGoogle Drive Folder: https://drive.google.com/drive/folders/12iWFuD8Dx8q-V7_t6Th4yS6HJd0o12NH

Name: Tam Tran
Email address: minhtam.tranthi@griffithuni.edu.au
Category: Sterile workflows (cell culture and related assays)
Robot: OT-2
Pipettes: p300 Single Channel,p10 8-Channel,p300 8-Channel  
Tips: Opentrons tips 
Modules: No modules are needed for this protocol
Labware: Standard labware (Fits within a standard microplate footprint. Example: 96 well plate, 384 well plate, automation-friendly trough, etc),Opentrons labware (Example: Opentrons 4-in-1 tuberack)
Custom Labware Description (if applicable): 
CSV (if applicable): 
Reagents (if applicable): The LIVE/DEAD® BacLight™ Bacterial Viability Kit will be used.
Additional Info: 

WORKFLOW DESCRIPTION
See GDoc in Drive folder

**Comment by Laura-Danielle** [comment]
Closed Sprint Week of 10/29

**Comment by ahiuchingau** [comment]
Sent preliminary protocol to user during Sprint Week of 10/29 - received a bunch of changes 
Reopening this issue and adding it to Spring Week of 11/26
