### ISSUE TITLE
[S] Marianna Jones at Dale Ramsden at UNC-Chapel Hill

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/Protocols#461]
https://trello.com/c/q1MDC9LE/1415-s-marianna-jones-at-dale-ramsden-at-unc-chapel-hill2018-11-05T17:00:00.000ZGoogle Drive Folder: https://drive.google.com/drive/folders/1OHLXQrOfr-9CwzMKhGG6KzmKBaffKXaV

Name: Marianna Jones
Email address: mkj@live.unc.edu
Category: PCR/qPCR prep
Robot: OT-2
Pipettes: p10 Single Channel,p10 8-Channel  
Tips: Other tips GeneMate 10ul filtered tips P-1237-10XL
Modules: No modules are needed for this protocol
Labware: Standard labware (Fits within a standard microplate footprint. Example: 96 well plate, 384 well plate, automation-friendly trough, etc),Opentrons labware (Example: Opentrons 4-in-1 tuberack),Custom labware (Choose this when you need us to create a file or adapter for something smaller/larger than a standard microplate footprint)
Custom Labware Description (if applicable): VWR 12 Channel Pipette Reservoir 80092-466
CSV (if applicable): 
Reagents (if applicable): Applied Biosystems TaqMan Fast Advanced qPCR https://www.thermofisher.com/order/catalog/product/4444963
Additional Info: https://s3-ap-southeast-2.amazonaws.com/paperform/u-4256/0/2018-10-25/bx13pjm/2018-10-22%20plate.xlsx

WORKFLOW DESCRIPTION
See GDoc in Drive folder

**Comment by ahiuchingau** [comment]
The user no longer needs this request as they found one on the library that is sufficient for their need.
