### ISSUE TITLE
[M] Felipe A. Millacura at Chris French Laboratory of Synthetic Biology and Microbial Biotechnology

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/Protocols#530]
https://trello.com/c/A0uCER6J/1457-m-felipe-a-millacura-at-chris-french-laboratory-of-synthetic-biology-and-microbial-biotechnology2019-01-07T17:00:00.000ZGoogle Drive Folder: https://drive.google.com/drive/folders/18mhQtdknzAKhOecn1e0ADSFnO4fs2bcM

Name: Felipe A. Millacura
Email address: f.millacura.a@gmail.com
Category: PCR/qPCR prep
Robot: OT-2
Pipettes: p10 Single Channel,p50 8-Channel  
Tips: Other tips StarLab tips, 10 uL graduated and 200 uL yellow  https://www.starlabgroup.com/GB-en/consumables/pipette-tips_WebPSub-155853/tipone-pipette-tips_PF-SL-154833.html
Modules: No modules are needed for this protocol
Labware: Standard labware (Fits within a standard microplate footprint. Example: 96 well plate, 384 well plate, automation-friendly trough, etc)
Custom Labware Description (if applicable): 
CSV (if applicable): 
Reagents (if applicable): Everything is homemade prepared, please have a look to the attached file
Additional Info: https://s3-ap-southeast-2.amazonaws.com/paperform/u-4256/0/2018-11-19/96131b1/Cell%20free%20TX-only%20and%20TX-TL%20system%20preparation.pdf

WORKFLOW DESCRIPTION
See GDoc in Drive folder

**Comment by Laura-Danielle** [comment]
Did not actually want protocol. Will write themselves.

**Comment by kristinellis** [comment]
Deleting this issue per user request; since user wrote protocol on their own and requested takedown.
