### ISSUE TITLE
[L] Romeo Lascaris at University of Applied Science Inholland

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/Protocols#627]
https://trello.com/c/HqysfD2V/1490-l-romeo-lascaris-at-university-of-applied-science-inholland2019-02-04T17:00:00.000ZGoogle Drive Folder: https://drive.google.com/drive/folders/1bxFaL2jZRe9yIxOecEhYZOyZx2J1tNoK

Name: Romeo Lascaris
Email address: romeo.lascaris@inholland.nl
Category: CSV/Excel File input (for protocols like normalization, cherry picking, DNA assembly, etc)
Robot: OT-2
Pipettes: p300 Single Channel,p50 Single Channel  
Tips: Opentrons tips 
Modules: No modules are needed for this protocol
Labware: Standard labware (Fits within a standard microplate footprint. Example: 96 well plate, 384 well plate, automation-friendly trough, etc),Opentrons labware (Example: Opentrons 4-in-1 tuberack)
Custom Labware Description (if applicable): 
CSV (if applicable): https://s3-ap-southeast-2.amazonaws.com/paperform/u-4256/0/2019-01-13/ne434de/RomeoLascaris_example_csv2py.csv
Reagents (if applicable): many compounds that have antibiotic properties
Additional Info: https://s3-ap-southeast-2.amazonaws.com/paperform/u-4256/0/2019-01-13/523341p/testDesign_6factors.txt

WORKFLOW DESCRIPTION
See GDoc in Drive foldercolor: red
id: 595663eb1314a339996db99e
idBoard: 584837f721836c285b124287
name: Needs clarification

**Comment by ahiuchingau** [comment]
Sent to customer directly
