### ISSUE TITLE
[M] Kacper Lachowski at Pozzo Lab / University of Washington

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/Protocols#699]
https://trello.com/c/wzOeJL9G/1517-m-kacper-lachowski-at-pozzo-lab-university-of-washington2019-03-04T17:00:00.000ZGoogle Drive Folder: https://drive.google.com/drive/folders/1adgDj9EPnVt0OmtWbTKzw_vRJBfI_5qc

Name: Kacper Lachowski
Email address: lachok@uw.edu
Category: CSV/Excel File input (for protocols like normalization, cherry picking, DNA assembly, etc)
Robot: OT-2
Pipettes: p1000 Single Channel,p300 Single Channel,p50 Single Channel  
Tips: Opentrons tips 
Modules: No modules are needed for this protocol,Temperature Module
Labware: Standard labware (Fits within a standard microplate footprint. Example: 96 well plate, 384 well plate, automation-friendly trough, etc),Opentrons labware (Example: Opentrons 4-in-1 tuberack),Custom labware (Choose this when you need us to create a file or adapter for something smaller/larger than a standard microplate footprint)
Custom Labware Description (if applicable): We are in the process of designing our own 96 well plate out of anodized aluminum (for post temperature treatment purposes) . Aside from the material, the well plate would have similar to identical specifications to a standard 96 well plate. 
CSV (if applicable): https://s3-ap-southeast-2.amazonaws.com/paperform/u-4256/0/2019-02-28/i203lr5/Opentrons%20Lipid%20Prep%20Example.xlsx
Reagents (if applicable): One example is ethanol, water. Another would require more viscous liquids (deep eutectic solvents) , which may need to be heated in order to reduce viscosity to facilitate pipetting.  On that note, what is the maximum viscosity the instrument can handle?

Please let us know whether you have tried "reverse pipetting", which is a work around for working with more viscous liquids. 
Additional Info: https://s3-ap-southeast-2.amazonaws.com/paperform/u-4256/0/2019-02-28/5k13l65/Opentrons%20Protocol%20Explanation.pptx

WORKFLOW DESCRIPTION
See GDoc in Drive foldercolor: orange
id: 59d79837f2750114989477c2
idBoard: 584837f721836c285b124287
name: Uses CSV

**Comment by ahiuchingau** [comment]
Issue archived as user no longer needs this.
