### ISSUE TITLE
[S] Minlee Kim at Genolution

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/Protocols#736]
Trello URL: https://trello.com/c/6e7YbyCn/1538-s-minlee-kim-at-genolution

Google Drive Folder: https://drive.google.com/drive/folders/1t8u7l-vOMSkAFlW8uqOONmAL6PgDj2jo

Category:  simple transfer
Robot: OT-2
Pipettes: p50 Single Channel,p1000 Single Channel  
Tips: Other tips SafeSeal micro tube 2ml, PP Order number: 72.695.500
https://www.sarstedt.com/en/products/laboratory/screw-cap-micro-tubes-reaction-tubes/reaction-tubes/product/72.695.500/
Modules: No modules are needed for this protocol
Labware: Opentrons labware (Example: Opentrons 4-in-1 tuberack)
Custom Labware Description (if applicable): standard conical tube
CSV (if applicable): 
Reagents (if applicable): Reagent in A3 of Tube Rack Stand with 15 & 50mL Tube Holder Top is phenol-like and viscose. (requires slow pipetting)
Additional Info: 

WORKFLOW DESCRIPTION
See GDoc in Drive folder

**Comment by ahiuchingau** [comment]
Using PD
