### ISSUE TITLE
[M] Ann Donnelly at University of Pittsburgh

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/Protocols#750]
Trello URL: https://trello.com/c/Vmm2J0Nh/1548-m-ann-donnelly-at-university-of-pittsburgh

Google Drive Folder: https://drive.google.com/drive/folders/1aHdho0NwgC81tSziFyYf-040jBuAul84

Category:  CSV/Excel File input (for protocols like normalization, cherry picking, DNA assembly, etc)
Robot: OT-2
Pipettes: p50 Single Channel,p300 Single Channel  
Tips: Opentrons tips 
Modules: No modules are needed for this protocol
Labware: Opentrons labware (Example: Opentrons 4-in-1 tuberack),Standard labware (Fits within a standard microplate footprint. Example: 96 well plate, 384 well plate, automation-friendly trough, etc)
Custom Labware Description (if applicable): Standard 15 mL and 50 mL falcon tubes e.g.
https://www.fishersci.com/shop/products/basix-polypropylene-centrifuge-tubes/p-6895041
CSV (if applicable): https://s3-ap-southeast-2.amazonaws.com/paperform/u-4256/0/2019-03-28/0b129s4/ex1x3.csv
Reagents (if applicable): 
Additional Info: 

WORKFLOW DESCRIPTION
See GDoc in Drive folder

**Comment by ahiuchingau** [comment]
@ncdiehl11 sent protocol to user via email
