### ISSUE TITLE
[XS] Chase Furler at SMSbiotech

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/Protocols#765]
Trello URL: https://trello.com/c/WhRSYKfx/1554-xs-chase-furler-at-smsbiotech

Google Drive Folder: https://drive.google.com/drive/folders/1VvNWUmbFWFBJGJwKI6cBEw-5Ved3oKvN

Category:  Sterile workflows (cell culture and related assays)
Robot: OT-One S Hood
Pipettes:  Only using One Channel Pipette on Axis B p1000 (100 - 1000 uL)
Tips:  
Modules: No modules are needed for this protocol
Labware: Standard labware (Fits within a standard microplate footprint. Example: 96 well plate, 384 well plate, automation-friendly trough, etc)
Custom Labware Description (if applicable): Tip= TipOne 1000ul sterile filtered tip, USA Scientific, 1126-7810
Plate= TPP tissue culture 24-well plate, Sigma Aldrich,  Z707791
Tip Waste= Undetermined
Liquid Waste = Undetermined
Trough = Undetermined
CSV (if applicable): 
Reagents (if applicable): M200 -https://www.thermofisher.com/order/catalog/product/M200500
Additional Info: 

WORKFLOW DESCRIPTION
See GDoc in Drive folder

**Comment by ahiuchingau** [comment]
sent to customer via email
