### ISSUE TITLE
Incorrect container referenced in fp_hts_run protocol?

### ISSUE THREAD

**Issue by jamesscottbrown** [OpenTrons/Protocols#77]
At [line 41 of the fp_hts_run protocol](https://github.com/OpenTrons/Protocols/blob/develop/fp_hts_run/fp_hts_run.py#L41), should ``for row in dilution_plate.rows('1', to='22')`` be ``for row in assay_plate.rows('1', to='22')``?

As written, it looks like ``alternate_dilution_columns`` and ``alternate_assay_columns`` are the same,  so there will be a problem with [the line](https://github.com/OpenTrons/Protocols/blob/develop/fp_hts_run/fp_hts_run.py#L72):

    # add diluted compunds to assay plate
    p10.transfer(1.2, alternate_dilution_columns, alternate_assay_columns)

**Comment by IanLondon** [comment]
Hey James! Thanks for raising this issue. I'll check it out.

**Comment by IanLondon** [comment]
Fixed in commit f61f874. Thanks!
