### ISSUE TITLE
[XXS] Kimnfriends at KIM&FRIENDS

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/Protocols#773]
Trello URL: https://trello.com/c/ta4pswU4/1558-xxs-kimnfriends-at-kimfriends

Google Drive Folder: https://drive.google.com/drive/folders/1C1noReX27WYrJwdp58N2CqXJXyzP-ry4

Category:  ----
Robot: OT-2
Pipettes: p1000 Single Channel,p300 8-Channel  
Tips: Opentrons tips 
Modules: Temperature Module
Labware: Standard labware (Fits within a standard microplate footprint. Example: 96 well plate, 384 well plate, automation-friendly trough, etc),Opentrons labware (Example: Opentrons 4-in-1 tuberack)
Custom Labware Description (if applicable): We have attached two protocols.
Can you combine these two protocols into one?

CSV (if applicable): 
Reagents (if applicable): ----
Additional Info: https://s3-ap-southeast-2.amazonaws.com/paperform/u-4256/0/2019-04-08/ae046ej/opentrons.zip

WORKFLOW DESCRIPTION
See GDoc in Drive folder

**Comment by ahiuchingau** [comment]
Protocol sent to user via email
