### ISSUE TITLE
Typo in container name?

### ISSUE THREAD

**Issue by jamesscottbrown** [OpenTrons/Protocols#78]
I think that on line 48  of the multiple sparse matrix screen protocol,``plate`` should be ``plate2``:

https://github.com/OpenTrons/Protocols/blob/bda060a7d8f3bfce7c81a782e6872a4494ff8c30/multiple_sparse_matrix_screens/multiple_sparse_matrix_screens.py#L48

**Comment by IanLondon** [comment]
Thanks James. Fixed in commit f61f874
