### ISSUE TITLE
[XS] Chase at SMSbiotech

### ISSUE THREAD

**Issue by Laura-Danielle** [Opentrons/Protocols#780]
Trello URL: https://trello.com/c/zBdRY1bK/1562-xs-chase-at-smsbiotech

Google Drive Folder: https://drive.google.com/drive/folders/1cpA8pY2nAuwGgHt8ptszhkruhhoug-Ae

Category:  Sterile workflows (cell culture and related assays)
Robot: OT-One S Hood
Pipettes:  None p1000 (100 - 1000 uL)
Tips:  
Modules: No modules are needed for this protocol
Labware: Opentrons labware (Example: Opentrons 4-in-1 tuberack)
Custom Labware Description (if applicable): Tip= TipOne 1000ul sterile filtered tip, USA Scientific, 1126-7810
Tuberack= TubeSpin 15ml  bioreactor conical tubes, TPP,  87015
Tip Waste= Undetermined
Liquid Waste = Undetermined
Trough = Undetermined
M200 -https://www.thermofisher.com/order/catalog/product/M200500

CSV (if applicable): 
Reagents (if applicable): M200 -https://www.thermofisher.com/order/catalog/product/M200500
Additional Info: 

WORKFLOW DESCRIPTION
See GDoc in Drive folder

**Comment by ahiuchingau** [comment]
sent to customer on 4/22
