### ISSUE TITLE
Communication with OT-2 via libssh2 suddenly stopped working

### ISSUE THREAD

**Issue by VincentBressler** [Opentrons/Protocols#964]
We use libssh2 to communicate with our OT-2 system. This has been working fine and today libssh2 fails to negotiate a communication handshake with the OT-2 system.

Nothing has changed on our end. 
We can communicate with the OT-2 via Opentrons and via Putty.
I think that our problem may be caused by a SSH protocol update for OT-2 systems in the field. 

Please let me know if the OT-2 SSH protocol has been updated in the last day or two. 

Thanks,
Vince

**Comment by ethanfjones** [comment]
Hello Vincent, 

Nothing has changed with the OT-2 SSH protocol in the past few days. Our last update to the robot's software was released on 05-29. All the changelogs can be found here https://github.com/Opentrons/opentrons/blob/edge/CHANGELOG.md

If you have any further support related questions please reach out to us via email (support@opentrons.com) or live chat.
